---
title: "01_Preprocessing"
author: "kim soyeon"
date: "2026-09-16"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 목표
```{r}
# if (!requireNamespace("devtools", quietly = TRUE)){install.packages("devtools")}
# pak::pak("jbisanz/qiime2R")
library(qiime2R)
library(phyloseq)
library(readr)
library(stringr)
library(ggplot2)
library(decontam)
library(ggpubr)
library(vegan)
library(dplyr)
library(RColorBrewer)
library(patchwork)
library(tibble)

# source("./Script/functions.R")

```


```{r}
getwd()

dir.create("./Phyloseq/")


```


# 1. import QIIME output


```{r}
# 16S
phy <- qiime2R::qza_to_phyloseq(
  features="./Input/test7_16S_V3V4/Output/05_trimm_optimal_GG2/F270_R210.table.qza",
  taxonomy="./Input/test7_16S_V3V4/Output/05_trimm_optimal_GG2/F270_R210.taxonomy.qza",
  tree ="./Input/test7_16S_V3V4/Output/07_phylogeny/rooted-tree.qza"
  ) #  4633 taxa and 73 samples


```






## 2) Make Metadata

```{r}
# 개인별 metadata는 저장소에 포함하지 않으며 별도로 준비한다.
meta3 <- readxl::read_xlsx("./Input/test7_16S_V3V4/metadata_private.xlsx") %>% data.frame()
```

```{r}
sample_names(phy)
rownames(meta3) <- meta3$Sample_ID

sample_data(phy) <-sample_data(meta3)

phy
saveRDS(phy, "./Phyloseq/phy_F270R210_260921.rds")
```

# 2.preprocessing

## 1) taxonomy name
```{r}

# tax$Genus %>% unique %>% sort

# Original version
tax_clean <- function(ps) {
  table <- data.frame(tax_table(ps))
  tax <- table[,c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")]
  tax

  # 2) NA -> ""
  tax[is.na(tax)] <- ""
  tax[tax=="__"] <- ""
  tax[tax=="NA"] <- ""
  tax[tax=="uncultured"] <- ""
  # tax[tax=="Unassigned"] <- ""
  # 3) paste [Unclassified + NA]
  tax_clean <- data.frame(tax)
  for (i in 1:nrow(tax_clean)){
    if (tax_clean[i,7] != ""){
      # tax_clean$Species[i] <- paste0(tax_clean$Genus[i],"_", tax_clean$Species[i]) # database에 따라 다름
      tax_clean$Species[i] <- str_replace(tax_clean$Species[i], " ", "_")
    } else if (tax_clean[i,2] == ""){
      kingdom <- paste0(tax_clean[i,1],"_k")
      tax_clean[i, 2:7] <- kingdom
    } else if (tax_clean[i,3] == ""){
      phylum <- paste0( tax_clean[i,2],"_p")
      tax_clean[i, 3:7] <- phylum
    } else if (tax_clean[i,4] == ""){
      class <- paste0( tax_clean[i,3],"_c")
      tax_clean[i, 4:7] <- class
    } else if (tax_clean[i,5] == ""){
      order <- paste0( tax_clean[i,4],"_o")
      tax_clean[i, 5:7] <- order
    } else if (tax_clean[i,6] == ""){
      family <- paste0( tax_clean[i,5],"_f")
      tax_clean[i, 6:7] <- family
    } else if (tax_clean[i,7] == ""){
      tax_clean$Species[i] <- paste0(tax_clean$Genus[i],"_g")
    }
  }
  print(tax_clean)
  tax_table(ps) <- tax_table(as.matrix(tax_clean))
  return(ps)
}


```


```{r}
# Mon Sep 21 15:08:08 2026 ------------------------------

tax <- tax_table(phy) |> data.frame()
tax$Kingdom <- str_replace(tax$Kingdom, "d__", "")
tax_table(phy)  <-tax_table(as.matrix(tax))

```


```{r}
phy2 <- tax_clean(phy)


tax <- tax_table(phy2) |> data.frame()
# View(tax)



tax$Kingdom |> table()

  # Bacteria Unassigned
  #     4629          4
```


## 2) Filter taxa
```{r}
# 1. Raw
phy2 #  4633  taxa

# 2. remove Unassigned and Eukaryota
phy3 <- subset_taxa(phy2, Kingdom == "Bacteria")  # 4629  taxa and 73  samples

# 3. remove chloroplast and mitochondria
phy3 <- subset_taxa(phy3, Class != "Chloroplast")  #  4602  taxa and 73 samples
phy3 <- subset_taxa(phy3, Family != "Mitochondria")  #  4583  taxa and 73 samples



phy3
# phyloseq-class experiment-level object
# otu_table()   OTU Table:         [ 4583 taxa and 73 samples ]
# sample_data() Sample Data:       [ 73 samples by 18 sample variables ]
# tax_table()   Taxonomy Table:    [ 4583 taxa by 7 taxonomic ranks ]
# phy_tree()    Phylogenetic Tree: [ 4583 tips and 4541 internal nodes ]

# saveRDS(phy3, "./Phyloseq/phy_F270R210_260921_v2.rds")
```

# 3. Decontam

## 1) Pre-decontamination quality check
## 2.1 Original Dataset

```{r}
summary(sample_sums(phy3))
# Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
#    3500   12558   37931   32478   46164   64323
```
